### ISSUE TITLE
export fbx error

### ISSUE THREAD

**Issue by csdjk** [javelinlin/Testing_CSV2Mesh_Tool#1]
![image](https://user-images.githubusercontent.com/33519787/178533692-d03e1c24-9bd0-44f7-bf92-f513efecd185.png)

configs:
![image](https://user-images.githubusercontent.com/33519787/178534481-a7559dd7-a25d-464d-aaf2-8683b337de72.png)

**Comment by javelinlin** [comment]
OK，明天看看



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月12日 23:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [javelinlin/Testing_CSV2Mesh_Tool] export fbx error (Issue #1) |

**Comment by javelinlin** [comment]
> ![image](https://user-images.githubusercontent.com/33519787/178533692-d03e1c24-9bd0-44f7-bf92-f513efecd185.png)
> 
> configs: ![image](https://user-images.githubusercontent.com/33519787/178534481-a7559dd7-a25d-464d-aaf2-8683b337de72.png)


---

**The Unity UV channel does not offer more than 7**

Unity Package : **FBX Export package** is based on **UnityEngine.Mesh** to do these...


---

大佬，我在知乎上见过你的名字（邮件名字）、头像，我就直接用中文描述吧

Unity Mesh 不能设置超过 uv7 之后的数据了。。。可能 unity 是为了性能优化考虑，才这么做的

如下是 UnityEngine.CoreModule.dll 中的 UnityEngine.Mesh 定义：
![image](https://user-images.githubusercontent.com/25763884/178629763-4dc9f3ba-f01d-4a09-a81b-cde39c211927.png)

如果可以的话，你可以将此 CSV 粘贴到这个 Issue 中 或是提供下载方式，我在本地看看是否可以提解决方案

**Comment by csdjk** [comment]
好的，谢谢了。百度网盘下吧

--来自百度网盘超级会员V6的分享
hi，这是我用百度网盘分享的内容~复制这段内容打开「百度网盘」APP即可获取 
链接:https://pan.baidu.com/s/1NS0omZGRDe2wbwa2hkD78A 
提取码:9917

**Comment by javelinlin** [comment]
> 好的，谢谢了。百度网盘下吧
> 
> --来自百度网盘超级会员V6的分享 hi，这是我用百度网盘分享的内容~复制这段内容打开「百度网盘」APP即可获取  链接:[https://pan.baidu.com/s/1NS0omZGRDe2wbwa2hkD78A ](https://pan.baidu.com/s/1NS0omZGRDe2wbwa2hkD78A%C2%A0) 提取码:9917

---
OK，我大概了解是什么问题了

你可能是从 ： RenderDoc 中的 Geometry 的 **Output** 数据导出的 CSV 所以 Texcoord 插值寄存器才会使用这么多
一般 Attribute 的（A2V）的寄存器不会有这么多

你可以再次尝试使用 RenderDoc Geometry **Input** 数据导出的 CSV 来尝试该工具转换

如果 使用 Input 数据后，有什么进展可以在该 Issue 继续留言

多谢反馈~

**Comment by csdjk** [comment]
> 
从Input 导出之前的问题没了，但是又有一个新问题了，有空的话再看看吧。23333

链接:https://pan.baidu.com/s/17uKSIHVP2XeN5KpXXh9pDQ 
提取码:0fs9

![image](https://user-images.githubusercontent.com/33519787/178672327-61254a89-0ca3-4f7a-aacb-deaa229d77cf.png)

**Comment by javelinlin** [comment]
> > 
> 
> 从Input 导出之前的问题没了，但是又有一个新问题了，有空的话再看看吧。23333
> 
> 链接:[https://pan.baidu.com/s/17uKSIHVP2XeN5KpXXh9pDQ ](https://pan.baidu.com/s/17uKSIHVP2XeN5KpXXh9pDQ%C2%A0) 提取码:0fs9
> 
> ![image](https://user-images.githubusercontent.com/33519787/178672327-61254a89-0ca3-4f7a-aacb-deaa229d77cf.png)

这份 csv 可能数据有问题, -_-!

为何连几何体的 POSITION semantic 点坐标集合都没有
而且IDX不是从 0 开始（虽然这个我可以使用 动态计算 offset 的方式来解决）
但是没有 POSITION 的话，几何体是看不到任何内容的（连光栅化出来的片源都没有, -_-!）

**Comment by csdjk** [comment]
难道是我导出的方式不对&nbsp;


李长龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月13日(星期三) 下午5:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [javelinlin/Testing_CSV2Mesh_Tool] export fbx error (Issue #1)





    
从Input 导出之前的问题没了，但是又有一个新问题了，有空的话再看看吧。23333
 
链接:https://pan.baidu.com/s/17uKSIHVP2XeN5KpXXh9pDQ&nbsp; 提取码:0fs9
 

  
这份 csv 可能数据有问题, -_-!
 
为何连几何体的 POSITION semantic 点坐标集合都没有
 而且IDX不是从 0 开始（虽然这个我可以使用 动态计算 offset 的方式来解决）
 但是没有 POSITION 的话，几何体是看不到任何内容的（连光栅化出来的片源都没有, -_-!）

**Comment by javelinlin** [comment]
有可能，你可以参考下面截图

CHN: 在MeshView窗口中->VS Input->表格内鼠标右键->Export VS Input to CSV
你可以看到我的截图中 IDX 是从 0 开始
并且有 POSITION 的 semantic 的内容
我的 RenderDoc 使用的版本为：v1.20 (built from [70676457](https://github.com/baldurk/renderdoc/commit/70676a57a4054e310e2550d12b6e0d6787da9495))

EN: in MeshView windows->VS Input->Mouse Right Click in VS Input table region->Export VS Input to CSV
U can see my picture, IDX is start at 0
And there is POSITION semantic contents
My RenderDoc version is : v1.20 (built from [70676457](https://github.com/baldurk/renderdoc/commit/70676a57a4054e310e2550d12b6e0d6787da9495))

你使用的 RenderDoc version 是多少？

> 

![image](https://user-images.githubusercontent.com/25763884/178701937-788e337a-c770-4690-b3cd-40a11015d8c9.png)

**Comment by javelinlin** [comment]
更新一下，我添加了一些功能，现在可以导出你的 亚索 模型了
添加了：
- IDX 可以不从 0 开始
- 还有 可以自定义 CSV 中 Semantic 的作用

如下图是导出来的结果：

### Scene 视图中
![image](https://user-images.githubusercontent.com/25763884/178956730-15407564-ec6d-45fc-abd1-ac829548cf96.png)

### Mesh Preview - Shaded
![image](https://user-images.githubusercontent.com/25763884/178956927-50492ede-4436-42a8-8abb-a67a35edda7c.png)

### Mesh Preview - UVLayout
![image](https://user-images.githubusercontent.com/25763884/178957025-0013861a-23e9-4015-8b26-3d80575273ba.png)

下面是导出的配置：
![image](https://user-images.githubusercontent.com/25763884/178957492-908d6bbd-c5f9-47a7-ad77-2c52b1e00c71.png)

**Comment by javelinlin** [comment]
我使用的是你之前那个带有 Texcoord10 （超过 UV7 的）数据，这份数据可能是从VS Output 数据，所以我设置了导出配置的 Transform

**Comment by javelinlin** [comment]
等你有空，测试一下，最好能反馈一下结果
如果没有其他的问题的话，我就 close issue 了

**Comment by csdjk** [comment]
导出来是空的。。。
![image](https://user-images.githubusercontent.com/33519787/178965008-4f467453-2517-44cb-b505-04acc2456327.png)

**Comment by javelinlin** [comment]
有对应的错误吗？
如果有，能提供上对应的 csv 下载 就更好了

**Comment by csdjk** [comment]
没有报错。。


链接:https://pan.baidu.com/s/1qczM-L0o42ijOent9ycASw 
提取码:xapu

**Comment by javelinlin** [comment]
多谢，再更新一下

效果如下：
![image](https://user-images.githubusercontent.com/25763884/178977461-5d104a72-9efb-40ba-8684-9a3a3c20a077.png)

配置如下：
![image](https://user-images.githubusercontent.com/25763884/178977567-f63dc34c-5a86-4b20-8b67-b42a17c0de78.png)
![image](https://user-images.githubusercontent.com/25763884/178977627-184d8213-c605-4142-bad3-2309e3e0c511.png)

**Comment by csdjk** [comment]
谢谢，可以了，每次导出都必须这么设置吗？
&nbsp;


李长龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月14日(星期四) 晚上8:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [javelinlin/Testing_CSV2Mesh_Tool] export fbx error (Issue #1)





 
多谢，再更新一下
 
效果如下：
 
 
配置如下：

**Comment by javelinlin** [comment]
可能 RenderDoc 识别不出来 POSITION Semantic 数据
或是这些游戏开发使用的是：Texcoord[N] 的通道数据来保存模型数据
再加上 shader 使用 Texcoord[N] 的方式来实现，确实不会有 POSITION 之类的 semantic
因此 RenderDoc 识别不出来也是正常的

这个需要手动去试验数据
因为这些 Semantic 真正要用来干嘛的，还得完全逆向完 shader，并了解其他每个通道的作用
你才能准确无误的设置 semantic 的类型

如果说我们抓帧的游戏模型比较多，那么可以考虑添加一个：Manually Mapping Semanic Type 的配置数据的导出、导入功能，这样可以减少同一种制作方式的重复设置

**Comment by csdjk** [comment]
好吧-.-，非常感谢
&nbsp;


李长龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月14日(星期四) 晚上8:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [javelinlin/Testing_CSV2Mesh_Tool] export fbx error (Issue #1)





 
可能 RenderDoc 识别不出来 POSITION Semantic 数据
 或是这些游戏开发使用的是：Texcoord[N] 的通道数据来保存模型数据
 再加上 shader 使用 Texcoord[N] 的方式来实现，确实不会有 POSITION 之类的 semantic
 因此 RenderDoc 识别不出来也是正常的
 
这个需要手动去试验数据
 因为这些 Semantic 真正要用来干嘛的，还得完全逆向完 shader，并了解其他每个通道的作用
 你才能准确无误的设置 semantic 的类型
 
如果说我们抓帧的游戏模型比较多，那么可以考虑添加一个：Manually Mapping Semanic Type 的配置数据的导出、导入功能，这样可以减少同一种制作方式的重复设置

**Comment by javelinlin** [comment]
:)，那么，这个 issue 我就 close 了，多谢反馈！

**Comment by csdjk** [comment]
好的
&nbsp;


李长龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月14日(星期四) 晚上8:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [javelinlin/Testing_CSV2Mesh_Tool] export fbx error (Issue #1)





 
:)，那么，这个 issue 我就 close 了，多谢反馈！

**Comment by csdjk** [comment]
是的，我就是这么导的，但是我换一个模型就能转换了。。。&nbsp;


李长龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月13日(星期三) 下午5:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [javelinlin/Testing_CSV2Mesh_Tool] export fbx error (Issue #1)





 
有可能，你可以
